/**
 * Map file extension to Prism language id for syntax highlighting.
 * Covers common and many niche languages supported by Prism.
 */
export const EXT_TO_LANG: Record<string, string> = {
  // Web
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  jsx: "jsx",
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  tsx: "tsx",
  vue: "markup",
  svelte: "markup",
  html: "markup",
  htm: "markup",
  css: "css",
  scss: "scss",
  sass: "sass",
  less: "less",
  // Data / config
  json: "json",
  json5: "json5",
  jsonc: "json",
  yaml: "yaml",
  yml: "yaml",
  xml: "markup",
  svg: "markup",
  toml: "toml",
  ini: "ini",
  env: "properties",
  properties: "properties",
  // Docs
  md: "markdown",
  markdown: "markdown",
  mdx: "markdown",
  rst: "rest",
  adoc: "asciidoc",
  asciidoc: "asciidoc",
  // Backend
  py: "python",
  pyw: "python",
  pyi: "python",
  rb: "ruby",
  go: "go",
  mod: "go-module",
  rs: "rust",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  scala: "scala",
  sc: "scala",
  cs: "csharp",
  cshtml: "cshtml",
  php: "php",
  php3: "php",
  php4: "php",
  php5: "php",
  phtml: "php",
  swift: "swift",
  // C/C++
  c: "c",
  h: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  hxx: "cpp",
  // Shell / scripts
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  fish: "bash",
  ps1: "powershell",
  psm1: "powershell",
  bat: "batch",
  cmd: "batch",
  // SQL / data
  sql: "sql",
  plsql: "plsql",
  // Other
  lua: "lua",
  r: "r",
  R: "r",
  dart: "dart",
  elm: "elm",
  ex: "elixir",
  exs: "elixir",
  erb: "erb",
  haml: "haml",
  pug: "pug",
  jade: "pug",
  graphql: "graphql",
  gql: "graphql",
  dockerfile: "docker",
  docker: "docker",
  makefile: "makefile",
  mk: "makefile",
  cmake: "cmake",
  gradle: "gradle",
  groovy: "groovy",
  clj: "clojure",
  cljs: "clojure",
  edn: "clojure",
  hs: "haskell",
  lhs: "haskell",
  ml: "ocaml",
  mli: "ocaml",
  fs: "fsharp",
  fsx: "fsharp",
  fsi: "fsharp",
  vb: "vbnet",
  vbs: "vbnet",
  zig: "zig",
  v: "v",
  nim: "nim",
  cr: "crystal",
  sol: "solidity",
  tf: "hcl",
  tfvars: "hcl",
  hcl: "hcl",
  proto: "protobuf",
  thrift: "thrift",
  diff: "diff",
  patch: "diff",
  log: "log",
  re: "reason",
  rei: "reason",
  res: "rescript",
  shader: "glsl",
  vert: "glsl",
  frag: "glsl",
  glsl: "glsl",
  wgsl: "wgsl",
  hlsl: "hlsl",
  nix: "nix",
  rbx: "lua",
  tex: "latex",
  sty: "latex",
  bib: "latex",
}

export function getLanguage(filePath: string): string {
  const ext = filePath.includes(".")
    ? filePath.slice(filePath.lastIndexOf(".") + 1).toLowerCase()
    : ""
  return EXT_TO_LANG[ext] ?? "markup"
}

export function getLanguageLabel(filePath: string): string {
  const lang = getLanguage(filePath)
  const labels: Record<string, string> = {
    javascript: "JavaScript",
    jsx: "JSX",
    typescript: "TypeScript",
    tsx: "TSX",
    python: "Python",
    markup: "HTML",
    css: "CSS",
    scss: "SCSS",
    sass: "Sass",
    less: "Less",
    json: "JSON",
    yaml: "YAML",
    markdown: "Markdown",
    bash: "Shell",
    c: "C",
    cpp: "C++",
    csharp: "C#",
    go: "Go",
    rust: "Rust",
    java: "Java",
    kotlin: "Kotlin",
    ruby: "Ruby",
    php: "PHP",
    swift: "Swift",
    sql: "SQL",
    docker: "Dockerfile",
    graphql: "GraphQL",
  }
  return labels[lang] ?? lang
}
