/**
 * Load Prism core, theme, line-numbers, and common language components
 * so syntax highlighting works for the source code viewer.
 */
import Prism from "prismjs"
import "prismjs/plugins/line-numbers/prism-line-numbers"
import "prismjs/themes/prism-tomorrow.css"
import "prismjs/plugins/line-numbers/prism-line-numbers.css"

// Core languages (required for others)
import "prismjs/components/prism-clike"
import "prismjs/components/prism-markup"
import "prismjs/components/prism-markup-templating"
import "prismjs/components/prism-css"
import "prismjs/components/prism-javascript"
import "prismjs/components/prism-typescript"

// Web
import "prismjs/components/prism-jsx"
import "prismjs/components/prism-tsx"

// Backend / general
import "prismjs/components/prism-python"
import "prismjs/components/prism-json"
import "prismjs/components/prism-json5"
import "prismjs/components/prism-yaml"
import "prismjs/components/prism-markdown"
import "prismjs/components/prism-bash"
import "prismjs/components/prism-c"
import "prismjs/components/prism-cpp"
import "prismjs/components/prism-csharp"
import "prismjs/components/prism-go"
import "prismjs/components/prism-rust"
import "prismjs/components/prism-java"
import "prismjs/components/prism-kotlin"
import "prismjs/components/prism-scala"
import "prismjs/components/prism-php"
import "prismjs/components/prism-ruby"
import "prismjs/components/prism-swift"
import "prismjs/components/prism-sql"
import "prismjs/components/prism-powershell"
import "prismjs/components/prism-batch"

// More
import "prismjs/components/prism-scss"
import "prismjs/components/prism-sass"
import "prismjs/components/prism-less"
import "prismjs/components/prism-graphql"
import "prismjs/components/prism-docker"
import "prismjs/components/prism-ini"
import "prismjs/components/prism-properties"
import "prismjs/components/prism-toml"
import "prismjs/components/prism-lua"
import "prismjs/components/prism-r"
import "prismjs/components/prism-dart"
import "prismjs/components/prism-elixir"
import "prismjs/components/prism-haml"
import "prismjs/components/prism-pug"
import "prismjs/components/prism-erb"
import "prismjs/components/prism-makefile"
import "prismjs/components/prism-cmake"
import "prismjs/components/prism-groovy"
import "prismjs/components/prism-gradle"
import "prismjs/components/prism-clojure"
import "prismjs/components/prism-haskell"
import "prismjs/components/prism-ocaml"
import "prismjs/components/prism-fsharp"
import "prismjs/components/prism-basic"
import "prismjs/components/prism-vbnet"
import "prismjs/components/prism-zig"
import "prismjs/components/prism-nim"
import "prismjs/components/prism-solidity"
import "prismjs/components/prism-hcl"
import "prismjs/components/prism-protobuf"
import "prismjs/components/prism-diff"
import "prismjs/components/prism-log"
import "prismjs/components/prism-reason"
import "prismjs/components/prism-rescript"
import "prismjs/components/prism-glsl"
import "prismjs/components/prism-wgsl"
import "prismjs/components/prism-hlsl"
import "prismjs/components/prism-nix"
import "prismjs/components/prism-latex"
import "prismjs/components/prism-rest"
import "prismjs/components/prism-asciidoc"
import "prismjs/components/prism-cshtml"
import "prismjs/components/prism-go-module"
import "prismjs/components/prism-plsql"
import "prismjs/components/prism-crystal"
import "prismjs/components/prism-v"
import "prismjs/components/prism-erlang"
import "prismjs/components/prism-elm"
import "prismjs/components/prism-perl"
import "prismjs/components/prism-liquid"
import "prismjs/components/prism-twig"
import "prismjs/components/prism-ejs"
import "prismjs/components/prism-handlebars"
import "prismjs/components/prism-mongodb"
import "prismjs/components/prism-nginx"
import "prismjs/components/prism-apacheconf"
import "prismjs/components/prism-git"
import "prismjs/components/prism-regex"
import "prismjs/components/prism-jsonp"

export { Prism }
